### ISSUE TITLE
Error: Cannot find module 'jsts'

### ISSUE THREAD

**Issue by LuanGDantas** [ginkgoch/node-shapefile#121]
- Made,
yarn add ginkgo ch-shapefile.

- Posteriorly,
import { Shapefile } from "ginkgoch-shapefile"
const statesShp = new Shapefile('src/shared/assets/nucleo3.shp').open();

 - When exercising, he presented the following error,

Error: Cannot find module 'jsts'

**Comment by jojo2357** [comment]
how did you solve this? Did you solve this?
